// DEMO DATA — fictional cruise line and ships (see README.md). Ports are real; fares, ships and dates
// are invented. Sailings repeat on the cadence below, generated by MockCruiseProvider.
module.exports = {
  line: 'Azure Meridian Cruises',
  ships: [
    { code: 'AZM', name: 'MS Azure Meridian', built: 2022, guests: 2100, scene: 'ship-large' },
    { code: 'COR', name: 'MS Coral Odyssey', built: 2019, guests: 1450, scene: 'ship-large' },
    { code: 'AUR', name: 'Aurora Seas', built: 2024, guests: 640, scene: 'ship-small' },
  ],
  itineraries: [
    {
      code: 'EMED7', name: 'Eastern Mediterranean Discovery', region: 'Eastern Mediterranean', ship: 'AZM', nights: 7,
      embark: 'Alexandria', cadence_days: 14, first_sailing: '2026-10-10',
      ports: [
        { day: 1, port: 'Alexandria', country: 'Egypt', depart: '18:00' },
        { day: 2, port: 'At sea', country: '' },
        { day: 3, port: 'Limassol', country: 'Cyprus', arrive: '08:00', depart: '17:00' },
        { day: 4, port: 'Rhodes', country: 'Greece', arrive: '09:00', depart: '18:00' },
        { day: 5, port: 'Santorini', country: 'Greece', arrive: '08:00', depart: '20:00' },
        { day: 6, port: 'Piraeus (Athens)', country: 'Greece', arrive: '07:00', depart: '19:00' },
        { day: 7, port: 'Heraklion', country: 'Greece', arrive: '10:00', depart: '18:00' },
        { day: 8, port: 'Alexandria', country: 'Egypt', arrive: '07:00' },
      ],
      cabins: [
        { code: 'IN', name: 'Inside', pp_usd: 690, sleeps: 2, features: ['Two lower beds', 'Private bathroom'] },
        { code: 'OV', name: 'Oceanview', pp_usd: 860, sleeps: 3, features: ['Picture window', 'Sitting area'] },
        { code: 'BA', name: 'Balcony', pp_usd: 1090, sleeps: 3, features: ['Private balcony', 'Sitting area'] },
        { code: 'SU', name: 'Suite', pp_usd: 1890, sleeps: 4, features: ['Large balcony', 'Butler service', 'Priority boarding'] },
      ],
      port_fees_pp_usd: 145, taxes_pp_usd: 62,
    },
    {
      code: 'GRK5', name: 'Greek Isles Escape', region: 'Greek Islands', ship: 'AUR', nights: 5,
      embark: 'Piraeus (Athens)', cadence_days: 7, first_sailing: '2026-10-06',
      ports: [
        { day: 1, port: 'Piraeus (Athens)', country: 'Greece', depart: '17:00' },
        { day: 2, port: 'Mykonos', country: 'Greece', arrive: '07:00', depart: '23:00' },
        { day: 3, port: 'Santorini', country: 'Greece', arrive: '08:00', depart: '19:00' },
        { day: 4, port: 'Milos', country: 'Greece', arrive: '09:00', depart: '17:00' },
        { day: 5, port: 'Nafplio', country: 'Greece', arrive: '08:00', depart: '16:00' },
        { day: 6, port: 'Piraeus (Athens)', country: 'Greece', arrive: '07:00' },
      ],
      cabins: [
        { code: 'OV', name: 'Oceanview', pp_usd: 940, sleeps: 2, features: ['Picture window'] },
        { code: 'BA', name: 'Veranda', pp_usd: 1240, sleeps: 2, features: ['Private veranda'] },
        { code: 'SU', name: 'Owner\'s Suite', pp_usd: 2350, sleeps: 3, features: ['Wraparound veranda', 'Butler service'] },
      ],
      port_fees_pp_usd: 110, taxes_pp_usd: 48,
    },
    {
      code: 'RED4', name: 'Red Sea Reefs', region: 'Red Sea', ship: 'COR', nights: 4,
      embark: 'Safaga (Hurghada)', cadence_days: 7, first_sailing: '2026-10-08',
      ports: [
        { day: 1, port: 'Safaga (Hurghada)', country: 'Egypt', depart: '18:00' },
        { day: 2, port: 'Sharm el-Sheikh', country: 'Egypt', arrive: '08:00', depart: '18:00' },
        { day: 3, port: 'Aqaba', country: 'Jordan', arrive: '07:00', depart: '22:00' },
        { day: 4, port: 'At sea', country: '' },
        { day: 5, port: 'Safaga (Hurghada)', country: 'Egypt', arrive: '07:00' },
      ],
      cabins: [
        { code: 'IN', name: 'Inside', pp_usd: 420, sleeps: 2, features: ['Two lower beds'] },
        { code: 'OV', name: 'Oceanview', pp_usd: 520, sleeps: 3, features: ['Picture window'] },
        { code: 'BA', name: 'Balcony', pp_usd: 690, sleeps: 3, features: ['Private balcony'] },
      ],
      port_fees_pp_usd: 85, taxes_pp_usd: 35,
    },
  ],
  cancel: { free_days: 60, late_penalty_pct: 50 },
};
